### ISSUE TITLE
ImportError: 'text_type'

### ISSUE THREAD

**Issue by fernandomontanher** [klahnakoski/mo-future#2]
I've installed the last version of mo-future (commit f26da100cd0fc1c0e81a356df606904da17e8d40) and got an error using mo-sql-parser: 
`from mo_future import binary_type, items, number_types, text_type ImportError: cannot import name 'text_type'`

**Comment by klahnakoski** [comment]
I will fix that shortly

**Comment by klahnakoski** [comment]
Thank you for reporting this.   The old moz-sql-parser will now work with the newest mo-future.  There is a new moz-sql-parser that will also work with the new mo-future.

https://github.com/klahnakoski/mo-future/commit/44ade01636e5d92c97ed01f5b807bd65e8968f9a

https://github.com/mozilla/moz-sql-parser/commit/a577abc1a029736d7a972b8edb2030ea1548510b
