### ISSUE TITLE
Jupyterlab support

### ISSUE THREAD

**Issue by mansenfranzen** [klahnakoski/mo-future#3]
Hi there,

`mo_futures` does not seem to work well with jupyterlab. Here is the originating issue from [moz-sql-parser](https://github.com/mozilla/moz-sql-parser/issues/134).

Essentially, jupyterlab seems to overwrite `sys.stdout` with an object that does not have an attribute named `buffer` which causes the following error:

```python
from moz_sql_parser import parse

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-a6b019a9c7ac> in <module>
----> 1 from moz_sql_parser import parse

~\.conda\envs\env_pybearer_dev\lib\site-packages\moz_sql_parser\__init__.py in <module>
     14 from threading import Lock
     15 
---> 16 from mo_future import binary_type, items, number_types, text
     17 from pyparsing import ParseException, ParseResults
     18 

~\.conda\envs\env_pybearer_dev\lib\site-packages\mo_future\__init__.py in <module>
     29 
     30 if PY3:
---> 31     STDOUT = sys.stdout.buffer
     32     STDERR = sys.stderr.buffer
     33 

AttributeError: 'OutStream' object has no attribute 'buffer'
```

Everything works fine if used within python repl or ipython without jupyterlab.

<details>
  <summary>Python environment</summary>
  
Python 3.6.10 Win10

ipykernel==5.1.4
ipython==7.13.0
jupyter-client==6.0.0
jupyter-core==4.6.3
mo-future==3.70.20151
moz-sql-parser==3.32.20026

</details>

**Comment by klahnakoski** [comment]
https://github.com/vpelletier/pprofile/commit/93a80a32e4ba1837b74886d8e1d043338aacd4cc

**Comment by klahnakoski** [comment]
https://github.com/vpelletier/pprofile/issues/16#issuecomment-249335903

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-future/pull/4

**Comment by klahnakoski** [comment]
Naive solution.  I would like a test to prevent regression: Specifically, what happens when `moz-sql-parser` attempts to write to `OutStream`

**Comment by mansenfranzen** [comment]
Thanks for the quick response.
